=== BlogLR/GACMIP/GeradorDeCodigo/src/geradorDeCodigos/modelo.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/modelo.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE bd SYSTEM "modelo.dtd">

    <bd>
    ...
    </bd>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT bd (tabela)*>
<!ATTLIST bd
    nome CDATA #IMPLIED
    xsi:schemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tabela (campo)*>
<!ATTLIST tabela
    primario CDATA #IMPLIED
    nome CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT campo EMPTY>
<!ATTLIST campo
    tamanho CDATA #IMPLIED
    func CDATA #IMPLIED
    tipo CDATA #IMPLIED
    nome CDATA #IMPLIED
  >

=== BlogLR/GACMIP/GeradorDeCodigo/src/geradorDeCodigos/modelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bd SYSTEM "modelo.dtd">
<bd nome="soveteria">
    <tabela nome="clientes" primario="idCliente">
        <campo nome="idCliente" tipo="inteiro"  func="auto-iclemento" />
        <campo nome="nome" tipo="texto" tamanho="50"/>
        <campo nome="telefone" tipo="texto" tamanho="12"/>
    </tabela>
    <tabela nome="venderores" primario="idVendedor">
        <campo nome="idVendedor" tipo="inteiro" func="auto" />
        <campo nome="nome" tipo="texto" tamanho="50"/>
        <campo nome="telefone" tipo="texto" tamanho="12"/>
    </tabela>
    <tabela nome="e">
        <campo nome="" func="" tamanho="1" tipo="inteiro"></campo>
    </tabela>
</bd>
